package org.droolsassert;
dialect 'mvel'

import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicInteger;

rule 'atomic int rule'
    when
        $atomicInteger: AtomicInteger()
    then
        $atomicInteger.incrementAndGet()
end

rule "complex name test /`';,._!@#&%^*=+-~| ${with}(and)[or]"
    when
        $atomicLong: AtomicLong()
    then
        $atomicLong.incrementAndGet()
end
