package org.droolsassert;
dialect 'mvel'

import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicInteger;

rule 'before'
    salience 1
    when
        $object: Object()
    then
        System.out.println('before rules: ' + $object)
end

rule 'atomic int rule'
    when
        $atomicInteger: AtomicInteger()
    then
        $atomicInteger.incrementAndGet()
end

rule 'atomic long rule'
    when
        $atomicLong: AtomicLong()
    then
        $atomicLong.incrementAndGet()
end

rule 'after'
    salience -1
    when
        $object: Object()
    then
        System.out.println('after rules: ' + $object)
end